FROM ubuntu:21.04

RUN dpkg --add-architecture i386 && apt-get update -qq && \
    apt-get clean

RUN apt-get install -y wget git vim zsh neovim curl gcc clang sshpass cmake make clang++
RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" &&  chsh -s /usr/bin/zsh

RUN echo "alias vi='nvim'" >> ~/.zshrc && cat > ~/.config/nvim/init.vim << EOF
" updated by GitNote
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath=&runtimepath
source ~/.vimrc
EOF

RUN curl -fLo ~/.vimrc --create-dirs https://gitee.com/zhangfuwen/GitNote/raw/master/vim/vimrc
RUN mkdir -p /data1/GitNote/vim/ && curl -fLo /data1/GitNote/vim/coc.vim --create-dirs https://gitee.com/zhangfuwen/GitNote/raw/master/vim/vimrc
RUN curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    
RUN vi +PlugInstall +qall && apt install -y ripgrep cppman ctags cscope



