FROM ubuntu:20.04

ENV ANDROID_NDK_HOME /opt/android-ndk
ENV ANDROID_NDK_VERSION r22
ENV GCE_METADATA_ROOT 127.0.0.1


# ------------------------------------------------------
# --- Install required tools

RUN apt-get update -qq && \
    apt-get clean

RUN ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
	export DEBIAN_FRONTEND=noninteractive && \
	apt install -y tzdata && \
	dpkg-reconfigure --frontend noninteractive tzdata


RUN apt-get install -y wget npm git vim zsh sudo neovim curl sshpass

RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> \
/etc/sudoers

# download
RUN mkdir /opt/tmp && \
    cd /opt/tmp && \
    wget -q https://nodejs.org/dist/v14.16.0/node-v14.16.0-linux-x64.tar.xz && \
# uncompress
    tar xvf node-v14.16.0-linux-x64.tar.xz && \
# move to its final location
    mv ./node-v14.16.0-linux-x64 /opt/ && \
# remove temp dir
    rm -rf /opt/tmp

# add to PATH
ENV PATH /opt/node-v14.16.0-linux-x64/bin:${PATH}

RUN npm install -g yarn

RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" &&  chsh -s /usr/bin/zsh

ENV GIT_SSH_VARIANT=ssh

