FROM ubuntu:20.04

ENV ANDROID_NDK_HOME /opt/android-ndk
ENV ANDROID_NDK_VERSION r22
ENV GCE_METADATA_ROOT 127.0.0.1


# ------------------------------------------------------
# --- Install required tools

RUN apt-get update -qq && \
    apt-get clean

RUN ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
	export DEBIAN_FRONTEND=noninteractive && \
	apt install -y tzdata && \
	dpkg-reconfigure --frontend noninteractive tzdata


RUN apt-get install -y wget git vim zsh sudo neovim curl gcc clang sshpass
RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" &&  chsh -s /usr/bin/zsh

