FROM debian:10

ENV ANDROID_NDK_HOME /opt/android-ndk
ENV ANDROID_NDK_VERSION r22
ENV GCE_METADATA_ROOT 127.0.0.1


# ------------------------------------------------------
# --- Install required tools
RUN echo "deb http://ftp.us.debian.org/debian sid main" >> /etc/apt/sources.list

RUN dpkg --add-architecture i386 && apt-get update -qq && \
    apt-get clean
    
RUN ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
	export DEBIAN_FRONTEND=noninteractive && \
	apt install -y tzdata && \
	dpkg-reconfigure --frontend noninteractive tzdata


RUN apt-get install -y wget git vim zsh sudo neovim curl gcc clang sshpass cmake
RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" &&  chsh -s /usr/bin/zsh

RUN apt-get install -y bison make zip git locales pkg-config \
curl autoconf automake autopoint libtool libtool-bin help2man texinfo intltool \
xfonts-utils xutils-dev libfontenc-dev libxkbfile-dev libxmuu-dev \
libjpeg-dev libpng-dev libpixman-1-dev libssl-dev libpciaccess-dev

RUN apt-get install -y android-sdk android-sdk-platform-23
ENV ANDROID_HOME=/usr/lib/android-sdk

RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> \
/etc/sudoers

ENV GIT_SSH_VARIANT=ssh
ENV PATH=${PATH}:/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin

RUN apt-get install -y software-properties-common && \
	apt-add-repository 'deb http://security.debian.org/debian-security stretch/updates main' && \
	apt-get update -qq && \
	apt install -y openjdk-8-jdk

ENV JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'

RUN mkdir /opt/android-sdk && \
cd /opt/android-sdk && \
curl --output sdk-tools-linux.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip && \
unzip sdk-tools-linux.zip && \
echo -ne "y" | ./tools/bin/sdkmanager --install 'build-tools;29.0.2' 'platform-tools' 'platforms;android-29' 'tools' 



