name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for android_app_dev
      run: docker build . --file Dockerfile --tag xjbcode/ci_docker_android_ndk:android_app_dev
